//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Checkin()
        {
            this.GuestSymptoms = new HashSet<GuestSymptom>();
            this.Temperatures = new HashSet<Temperature>();
        }
    
        public int CheckinId { get; set; }
        public System.DateTime CheckinDate { get; set; }
        public string HotelCode { get; set; }
        public string PhoneNumber { get; set; }
        public int EntranceId { get; set; }
    
        public virtual Entrance Entrance { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuestSymptom> GuestSymptoms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temperature> Temperatures { get; set; }
    }
}
