//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Checkin> Checkins { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Entrance> Entrances { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<GuestSymptom> GuestSymptoms { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Symptom> Symptoms { get; set; }
        public virtual DbSet<Temperature> Temperatures { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
    }
}
