//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestSymptom
    {
        public int Id { get; set; }
        public int SymptomId { get; set; }
        public Nullable<int> CheckinId { get; set; }
    
        public virtual Checkin Checkin { get; set; }
        public virtual Symptom Symptom { get; set; }
    }
}
